[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.150.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.150.0"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
